# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chen/Desktop/DataStructure

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chen/Desktop/DataStructure

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chen/Desktop/DataStructure/CMakeFiles /Users/chen/Desktop/DataStructure//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chen/Desktop/DataStructure/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BST

# Build rule for target.
BST: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BST
.PHONY : BST

# fast build rule for target.
BST/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BST.dir/build.make CMakeFiles/BST.dir/build
.PHONY : BST/fast

#=============================================================================
# Target rules for targets named Huffman

# Build rule for target.
Huffman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Huffman
.PHONY : Huffman

# fast build rule for target.
Huffman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Huffman.dir/build.make CMakeFiles/Huffman.dir/build
.PHONY : Huffman/fast

#=============================================================================
# Target rules for targets named Heap

# Build rule for target.
Heap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Heap
.PHONY : Heap

# fast build rule for target.
Heap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Heap.dir/build.make CMakeFiles/Heap.dir/build
.PHONY : Heap/fast

#=============================================================================
# Target rules for targets named List

# Build rule for target.
List: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 List
.PHONY : List

# fast build rule for target.
List/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/List.dir/build.make CMakeFiles/List.dir/build
.PHONY : List/fast

#=============================================================================
# Target rules for targets named Hash

# Build rule for target.
Hash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hash
.PHONY : Hash

# fast build rule for target.
Hash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hash.dir/build.make CMakeFiles/Hash.dir/build
.PHONY : Hash/fast

#=============================================================================
# Target rules for targets named Bfind

# Build rule for target.
Bfind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bfind
.PHONY : Bfind

# fast build rule for target.
Bfind/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bfind.dir/build.make CMakeFiles/Bfind.dir/build
.PHONY : Bfind/fast

Find/Bfind.o: Find/Bfind.cpp.o
.PHONY : Find/Bfind.o

# target to build an object file
Find/Bfind.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bfind.dir/build.make CMakeFiles/Bfind.dir/Find/Bfind.cpp.o
.PHONY : Find/Bfind.cpp.o

Find/Bfind.i: Find/Bfind.cpp.i
.PHONY : Find/Bfind.i

# target to preprocess a source file
Find/Bfind.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bfind.dir/build.make CMakeFiles/Bfind.dir/Find/Bfind.cpp.i
.PHONY : Find/Bfind.cpp.i

Find/Bfind.s: Find/Bfind.cpp.s
.PHONY : Find/Bfind.s

# target to generate assembly for a file
Find/Bfind.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bfind.dir/build.make CMakeFiles/Bfind.dir/Find/Bfind.cpp.s
.PHONY : Find/Bfind.cpp.s

Find/Hash.o: Find/Hash.cpp.o
.PHONY : Find/Hash.o

# target to build an object file
Find/Hash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hash.dir/build.make CMakeFiles/Hash.dir/Find/Hash.cpp.o
.PHONY : Find/Hash.cpp.o

Find/Hash.i: Find/Hash.cpp.i
.PHONY : Find/Hash.i

# target to preprocess a source file
Find/Hash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hash.dir/build.make CMakeFiles/Hash.dir/Find/Hash.cpp.i
.PHONY : Find/Hash.cpp.i

Find/Hash.s: Find/Hash.cpp.s
.PHONY : Find/Hash.s

# target to generate assembly for a file
Find/Hash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hash.dir/build.make CMakeFiles/Hash.dir/Find/Hash.cpp.s
.PHONY : Find/Hash.cpp.s

Liner/LinkedList.o: Liner/LinkedList.cpp.o
.PHONY : Liner/LinkedList.o

# target to build an object file
Liner/LinkedList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/List.dir/build.make CMakeFiles/List.dir/Liner/LinkedList.cpp.o
.PHONY : Liner/LinkedList.cpp.o

Liner/LinkedList.i: Liner/LinkedList.cpp.i
.PHONY : Liner/LinkedList.i

# target to preprocess a source file
Liner/LinkedList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/List.dir/build.make CMakeFiles/List.dir/Liner/LinkedList.cpp.i
.PHONY : Liner/LinkedList.cpp.i

Liner/LinkedList.s: Liner/LinkedList.cpp.s
.PHONY : Liner/LinkedList.s

# target to generate assembly for a file
Liner/LinkedList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/List.dir/build.make CMakeFiles/List.dir/Liner/LinkedList.cpp.s
.PHONY : Liner/LinkedList.cpp.s

Tree/BST.o: Tree/BST.cpp.o
.PHONY : Tree/BST.o

# target to build an object file
Tree/BST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BST.dir/build.make CMakeFiles/BST.dir/Tree/BST.cpp.o
.PHONY : Tree/BST.cpp.o

Tree/BST.i: Tree/BST.cpp.i
.PHONY : Tree/BST.i

# target to preprocess a source file
Tree/BST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BST.dir/build.make CMakeFiles/BST.dir/Tree/BST.cpp.i
.PHONY : Tree/BST.cpp.i

Tree/BST.s: Tree/BST.cpp.s
.PHONY : Tree/BST.s

# target to generate assembly for a file
Tree/BST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BST.dir/build.make CMakeFiles/BST.dir/Tree/BST.cpp.s
.PHONY : Tree/BST.cpp.s

Tree/Heap.o: Tree/Heap.cpp.o
.PHONY : Tree/Heap.o

# target to build an object file
Tree/Heap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Heap.dir/build.make CMakeFiles/Heap.dir/Tree/Heap.cpp.o
.PHONY : Tree/Heap.cpp.o

Tree/Heap.i: Tree/Heap.cpp.i
.PHONY : Tree/Heap.i

# target to preprocess a source file
Tree/Heap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Heap.dir/build.make CMakeFiles/Heap.dir/Tree/Heap.cpp.i
.PHONY : Tree/Heap.cpp.i

Tree/Heap.s: Tree/Heap.cpp.s
.PHONY : Tree/Heap.s

# target to generate assembly for a file
Tree/Heap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Heap.dir/build.make CMakeFiles/Heap.dir/Tree/Heap.cpp.s
.PHONY : Tree/Heap.cpp.s

Tree/Huffman.o: Tree/Huffman.cpp.o
.PHONY : Tree/Huffman.o

# target to build an object file
Tree/Huffman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Huffman.dir/build.make CMakeFiles/Huffman.dir/Tree/Huffman.cpp.o
.PHONY : Tree/Huffman.cpp.o

Tree/Huffman.i: Tree/Huffman.cpp.i
.PHONY : Tree/Huffman.i

# target to preprocess a source file
Tree/Huffman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Huffman.dir/build.make CMakeFiles/Huffman.dir/Tree/Huffman.cpp.i
.PHONY : Tree/Huffman.cpp.i

Tree/Huffman.s: Tree/Huffman.cpp.s
.PHONY : Tree/Huffman.s

# target to generate assembly for a file
Tree/Huffman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Huffman.dir/build.make CMakeFiles/Huffman.dir/Tree/Huffman.cpp.s
.PHONY : Tree/Huffman.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BST"
	@echo "... Bfind"
	@echo "... Hash"
	@echo "... Heap"
	@echo "... Huffman"
	@echo "... List"
	@echo "... Find/Bfind.o"
	@echo "... Find/Bfind.i"
	@echo "... Find/Bfind.s"
	@echo "... Find/Hash.o"
	@echo "... Find/Hash.i"
	@echo "... Find/Hash.s"
	@echo "... Liner/LinkedList.o"
	@echo "... Liner/LinkedList.i"
	@echo "... Liner/LinkedList.s"
	@echo "... Tree/BST.o"
	@echo "... Tree/BST.i"
	@echo "... Tree/BST.s"
	@echo "... Tree/Heap.o"
	@echo "... Tree/Heap.i"
	@echo "... Tree/Heap.s"
	@echo "... Tree/Huffman.o"
	@echo "... Tree/Huffman.i"
	@echo "... Tree/Huffman.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

